# Generated by Django 2.2.16 on 2021-04-15 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0002_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='profile',
        ),
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
