# Generated by Django 2.2.16 on 2021-04-14 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attic', '0003_auto_20210414_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('time', models.TimeField(default='')),
                ('comment', models.CharField(default='', max_length=150)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Working', 'Working'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Open', max_length=10)),
                ('profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Attic.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult_date', models.DateField(default='')),
                ('consult_time', models.TimeField(default='')),
                ('consultation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Attic.Consultation')),
                ('profile', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Attic.Profile')),
            ],
        ),
    ]
