# Generated by Django 2.2.16 on 2021-04-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUps',
        ),
    ]
