# Generated by Django 2.2.16 on 2021-03-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('service_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField(max_length=5)),
                ('phone_number', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Consulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default='')),
                ('service_time', models.TimeField(default='')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Attic.Profile')),
            ],
        ),
    ]
