# Generated by Django 2.2.16 on 2021-05-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.CharField(choices=[('Pest: Mice', 'Pest: Mice'), ('Pest: Rats', 'Pest: Rats'), ('Pest: Racoons', 'Pest: Racoons'), ('Pest: Squirrels', 'Pest: Squirrels'), ('Pest: Skunks', 'Pest: Skunks'), ('Pest: Opossums', 'Pest: Opossums'), ('Pest: Snakes', 'Pest: Snakes'), ('Pest: Bats', 'Pest: Bats'), ('Pest: Birds', 'Pest: Birds'), ('Pest: Insects', 'Pest: Insects'), ('Insulation Install', 'Insulation Install'), ('Roofing Repair', 'Roofing Repair'), ('Construction', 'Construction'), ('Sheet Rock', 'Sheet Rock'), ('Cement Small Jobs', 'Cement Small Jobs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Working', 'Working'), ('Pending Customer', 'Pending Customer'), ('Customer', 'Customer')], default='New', max_length=20),
        ),
    ]
