# Generated by Django 2.2.16 on 2021-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attic', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consult_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consult_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
